### ISSUE TITLE
Feature Request: create/run sub-generators

### ISSUE THREAD

**Issue by warang580** [FreeAllMedia/stimpak#30]
I was reading Yeoman documentation and I saw this : 

> Generators scaffolding complex frameworks are likely to provide additional generators to scaffold smaller parts of a project. These generators are usually referred to as sub-generators, and are accessed as `generator:sub-generator`.
> 
> Take generator-angular as an example. Once the full angular app has been generated, other features can be added. To add a new controller to the project, run the controller sub-generator:
> 
> `$ yo angular:controller MyNewController`

Is it possible in Stimpak to make and run "sub-generators" ? Or something that would behave in a similar manner ?

**Comment by dcrockwell** [comment]
### Combine Generators

You can `.use()` any other stimpak generator in your own generator, and it will seamlessly integrate all of it's features with your own:

``` javascript
import StimpakNpm from "stimpak-npm";
import StimpakTestDriven from "stimpak-test-driven";

export default class MyGenerator {
    setup(stimpak) {
        stimpak.use(
            StimpakNpm,
            StimpakTestDriven
        )
        .then(this.showAnswers);
    }

    showAnswers(stimpak) {
        stimpak.answers(); // All answers from stimpak-npm and stimpak-test-driven
    }
}
```

**Comment by dcrockwell** [comment]
You can also combine generators on-the-fly via the cli:

``` shell
$ npm install stimpak-npm stimpak-test-driven -g --production

...

$ stimpak npm test-driven
```

**Comment by dcrockwell** [comment]
Let me know if this is the same as what you were thinking

**Comment by dcrockwell** [comment]
This has the latest docs: https://github.com/FreeAllMedia/stimpak/tree/feature/readme

**Comment by dcrockwell** [comment]
I'm currently working on: https://github.com/FreeAllMedia/stimpak/blob/feature/readme/GENERATORS.md

So if there's anything I can elaborate on in this guide, please let me know.

**Comment by dcrockwell** [comment]
Re-open if this is still an issue.
